name: "Create Release | jcdcdev"
description: "Creates a GitHub Release with automated changelog"
author: "James Carter"
branding:
  icon: "tag"
  color: "gray-dark"
inputs:
  version:
    description: "Version"
    required: true
  github-token:
    description: "GitHub Token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: jcdcdev/jcdcdev.Github.GenerateChangelog@main
      id: changelog
      with:
        target-version: ${{ inputs.version }}
        github-token: ${{ inputs.github-token }}
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        omitNameDuringUpdate: true
        token: ${{ inputs.github-token }}
        name: ${{ inputs.version }}
        tag: ${{ inputs.version }}
        body: ${{ steps.changelog.outputs.changelog }}
