name: "Create Release | jcdcdev"
description: "Creates a GitHub Release with automated changelog"
author: "James Carter"
branding:
  icon: "tag"
  color: "gray-dark"
inputs:
  version:
    description: "Version"
    required: true
  github-token:
    description: "GitHub Token"
    required: true
  artifacts:
    description: "An optional set of paths representing artifacts to upload to the release. This may be a single path or a comma delimited list of paths (or globs)"
    required: false
    default: ""
outputs:
  changelog:
    description: "Changelog"
    value: ${{ steps.changelog.outputs.changelog }}
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Create tag
      shell: bash
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        git tag -fa ${{ inputs.version }} -m "Release ${{ inputs.version }}"
        git push --force origin ${{ inputs.version }}
    - uses: jcdcdev/jcdcdev.Github.GenerateChangelog@main
      id: changelog
      with:
        version: ${{ inputs.version }}
        github-token: ${{ inputs.github-token }}
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        omitNameDuringUpdate: true
        artifacts: ${{ inputs.artifacts }}
        token: ${{ inputs.github-token }}
        name: ${{ inputs.version }}
        tag: ${{ inputs.version }}
        body: ${{ steps.changelog.outputs.changelog }}
