name: "Create Release | jcdcdev"
description: "Creates a GitHub Release with automated changelog"
author: "James Carter"
branding:
  icon: "tag"
  color: "gray-dark"
inputs:
  version:
    description: "Version"
    required: true
  github-token:
    description: "GitHub Token"
    required: true
  artifact-name:
    description: "An optional artifact name to upload to the release."
    required: false
    default: ""
outputs:
  changelog:
    description: "Changelog"
    value: ${{ steps.changelog.outputs.changelog }}
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Create tag if not exists
      shell: bash
      run: |
        git fetch --tags
 
        if git tag -l | grep -q "^${{ inputs.version }}$"; then
          echo "Tag exists"
          exit 0
        fi

        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        git tag -fa ${{ inputs.version }} -m "Release ${{ inputs.version }}"
        git push --force origin ${{ inputs.version }}
    - uses: jcdcdev/jcdcdev.Github.GenerateChangelog@main
      id: changelog
      with:
        version: ${{ inputs.version }}
        github-token: ${{ inputs.github-token }}
    - name: Download package
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ github.workspace }}/artifact
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        omitNameDuringUpdate: true
        artifacts: ${{ github.workspace }}/artifact/*
        token: ${{ inputs.github-token }}
        name: ${{ inputs.version }}
        tag: ${{ inputs.version }}
        body: ${{ steps.changelog.outputs.changelog }}
